# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
