# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20160823_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
