# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='read_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
