# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='draft',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='genre',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='draft',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
